export enum ProviderType {
  GOOGLE_DRIVE = 'GOOGLE_DRIVE',
  ONEDRIVE = 'ONEDRIVE',
  TELEGRAM = 'TELEGRAM',
  CLOUDINARY = 'CLOUDINARY',
  MEGA = 'MEGA',
  DROPBOX = 'DROPBOX',
  BOX = 'BOX',
  PCLOUD = 'PCLOUD',
  YANDEX = 'YANDEX',
  VPS = 'VPS',
  LOCAL_MACHINE = 'LOCAL_MACHINE',
}
